ENEMY_ASCII = [
    [
        "   WATCHING YOU   ",
        "  /      |      \\ ",
        " /       |       \\",
        "| THEY'RE|   ALL  |",
        "| STARING|AT YOU  |",
        " \\ CAN'T | TRUST  /",
        "  \\------|------/ ",
    ],
    [
        "      DESPITE      ",
        "  /      |      \\ ",
        " /   EVERYTHING  \\",
        "|       IS        |",
        "|    IT   STILL   |",
        " \\    YOU?       /",
        "  \\------|------/ ",
    ],
    [
        "    ARE THEY     ",
        "  /      |      \\ ",
        " /       |       \\",
        "| SINCERE|OR IS IT|",
        "| ALL JUST  LIES  |",
        " \\  LIES |  LIES  /",
        "  \\------|------/ ",
    ],
    [
        " THEY'LL HURT YOU ",
        "  /      |      \\ ",
        " /       |       \\",
        "| KEEP   |   YOUR |",
        "| DISTANCE ALWAYS |",
        " \\       |       /",
        "  \\------|------/ ",
    ],
]

DEATH_ASCII = [
    [
        "  IT'S...        ",
        "     TOO...      ",
        "        MUCH...  ",
        "                 ",
        "   F A D I N G   ",
    ],
    [
        " THE WALLS...    ",
        "    ARE...       ",
        "       CRUMBLING ",
        "                 ",
        "   A L O N E . . .",
    ],
    [
        "  BROKEN...      ",
        "     TRUST...    ",
        "        ...      ",
        "                 ",
        "   S H A T T E R E D ",
    ],
    [
        "  NOTHING...     ",
        "     LEFT...     ",
        "        ...      ",
        "                 ",
        "   E M P T Y . . .",
    ],
]

BOSS_ASCII = [
    "      EVERYONE HAS AN AGENDA      ",
    "     /                        \\     ",
    "    /   THEY DON'T REALLY    \\    ",
    "   |          CARE ABOUT YOU  |   ",
    "   \\                        /   ",
    "    ------NO ONE IS SAFE------    ",
    "   /          ||          \\   ",
    "  / PROTECT   ||   YOURSELF \\  ",
    " |            ||            | ",
    " \\   KEEP     ||     GUARDED / ",
    "  \\          ||          /  ",
    "   ----YOU'RE BETTER OFF----   ",
    "  /           ALONE         \\  ",
    " |                           | ",
    " \\      IT'S THE ONLY WAY    / ",
    "  \\_________________________/  ",
]

BOSS_DEATH_ASCII = [
    "      .........      ",
    "     .         .     ",
    "    .  B U T   .     ",
    "   .    .      .    ",
    "  .   N O B O D Y .  ",
    " .     . .       . ",
    ".     C A M E     .",
    " .      .        . ",
    "  . . . . . . . .  ",
    "     .     .       ",
    "      .   .        ",
    "       . .         ",
    "        .          ",
]